const CANVAS_WIDTH = 768;
const CANVAS_HEIGHT = 432;
const STATES = {
  STILL: 0,
  RUNNING: 1,
  JUMPING: 2,
  FALLING: 3,
};
const IMG_HEARTS = {
  FULL: 0,
  HALF: 1,
  EMPTY: 2,
};


export { CANVAS_WIDTH, CANVAS_HEIGHT, STATES, IMG_HEARTS}